global:
  smtp_smarthost: "localhost:25"
  smtp_from: "alertmanager@example.org"
  smtp_auth_username: "alertmanager"
  smtp_auth_password: "xxxx"

templates:
  - "notification_template.tmpl"

receivers:
  - name: "default"
    email_configs:
      - to: "all@foo.bar"
  - name: "team-A"
    email_configs:
      - to: "team-a@foo.bar"
  - name: "team-B"
    email_configs:
      - to: "team-b@foo.bar"

route:
  group_by: ["alertname", "cluster", "service"]
  receiver: "default"
  routes:
    - matchers:
        - team="team-A"
      receiver: team-A
    - matchers:
        - team="team-B"
      receiver: team-B
